general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    border_size = 2
    #no_border_on_floating = true
    gaps_in = 5
    gaps_out = 20
    gaps_workspaces = 20
    col.inactive_border = rgba(595959aa)
    col.active_border = rgba(334488ee) rgba(008844ee) 45deg

    layout = dwindle
}

decoration {

  ## Rounded Corner
    rounding = 4
    # multisample_edges = true

  ## Opacity
    active_opacity = 1.0
    inactive_opacity = 0.8
    fullscreen_opacity = 1.0

  ## blur
    blur {
        enabled = true
        size = 4
        passes = 3
        ignore_opacity = true
        new_optimizations = true
        xray = true
    }

  ## Shadow
    shadow {
        enabled = true
        color = 0x66404040
        ignore_window = true
        offset = 1 2
        range = 10
        render_power = 3
    }
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

