#===================
# Key Bind
#===================

# Prefix
# デフォルトのPrefix(C-b)を解除
unbind C-b
set -g prefix C-f
bind C-w send-prefix

# コピー、選択モードのキーバインドvi/emacs
set-window-option -g mode-keys vi
bind-key -t vi-copy v begin-selection

bind Space copy-mode
bind p paste-buffer

# vでマーク開始
bind -t vi-copy v begin-selection
# Vで行の先頭からマーク開始
bind -t vi-copy V select-line
# C-vで矩形選択の切り替え
bind -t vi-copy C-v rectangle-toggle
# yでヤンク
bind -t vi-copy y copy-selection
# Yで1行ヤンク
#bind -t vi-copy Y copy-linebegin-selection

# 直前のウィンドウ
bind u last-window
# 設定リロード
bind r source-file ~/.tmux.conf

bind - split-window -v
bind \ split-window -h

# move around panes with hjkl, as one would in vim after pressing ctrl-w
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n S-left select-pane -L
bind -n S-down select-pane -D
bind -n S-up select-pane -U
bind -n S-right select-pane -R
# resize panes like vim
# feel free to change the "1" to however many lines you want to resize by, only
# one at a time can be slow

bind C-h resize-pane -L 20
bind C-l resize-pane -R 20
bind C-j resize-pane -D 20
bind C-k resize-pane -U 20

bind < resize-pane -L 15
bind > resize-pane -R 15
bind ( resize-pane -L 5
bind ) resize-pane -R 5
bind _ resize-pane -D 10
bind + resize-pane -U 10
# bind : to command-prompt like vim
# this is the default in tmux already
bind : command-prompt
unbind-key \;
bind \; command-prompt


#===================
# Option
#===================

# utf8有効
set-window-option -g utf8 on

set-option -g default-shell /bin/zsh
set-option -g default-command /bin/zsh
# マウス有効。MacのTerminal.appでは効かず…
set-option -g mouse-select-pane on
# #マウススクロール反映
set-window-option -g mode-mouse on

#ESCの反応速度向上
set -s escape-time 0
#window count:1 Order
set-option -g base-index 1

# 異なるサイズの端末からアクセスした時にリサイズ
setw -g aggressive-resize on


#===================
# Theme
#===================

# 256color
set-option -g default-terminal screen-256color
set -g default-terminal "xterm-256color"
set -g terminal-overrides "term:colors=256"
set -g display-time 2000


# Status line
set-option -g status on
set-option -g status-position top
set-option -g status-interval 30
set-option -g status-utf8 on
set-option -g status-justify "left"
set-option -g status-left-length 20
set-option -g status-right-length 90

set -g status-fg default
set -g status-bg default

# Pane border
set-option -g pane-border-fg cyan #base02
#set-option -g pane-border-bg default #base02
set-option -g pane-active-border-fg cyan #base01
#set-option -g pane-active-border-bg default #base01
#set -g monitor-activity on
#set -g visual-activity on

#special character ◉❖ ❯  ⏺ •
set-option -g status-left '#[fg=red,bold]❯#[fg=yellow,bold]❯#[fg=blue,bold]❯#[fg=default,bg=default,bold] #20 Session: #S#[fg=blue,bg=default,nobold]  ❯#[default]'
set-option -g status-right "#[fg=default,bg=default,bold]❖ #(hostname -s) %Y/%m/%d %H:%M"
set-window-option -g window-status-current-format "#[fg=default, bg=default] #I: #W❯ "
set -g window-status-format "#[fg=blue,bg=default] #I: #W❯ "
